# Generated by Django 2.0.9 on 2019-01-31 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20190130_2048'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='telegram_photo_file_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
