# Generated by Django 2.0.9 on 2018-12-31 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='telegram_user_id',
            field=models.IntegerField(blank=True, null=True, verbose_name='Telegram ID'),
        ),
        migrations.AddField(
            model_name='user',
            name='telegram_username',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Telegram username'),
        ),
    ]
